/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef ORG_OPENNI_NATIVEMETHODS_H
#define ORG_OPENNI_NATIVEMETHODS_H

#include <jni.h>
/* Header for class org_openni_NativeMethods */

#ifndef _Included_org_openni_NativeMethods
#define _Included_org_openni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
#undef org_openni_NativeMethods_STATUS_OK
#define org_openni_NativeMethods_STATUS_OK 0L
#undef org_openni_NativeMethods_STATUS_ERROR
#define org_openni_NativeMethods_STATUS_ERROR 1L
#undef org_openni_NativeMethods_STATUS_NOT_IMPLEMENTED
#define org_openni_NativeMethods_STATUS_NOT_IMPLEMENTED 2L
#undef org_openni_NativeMethods_STATUS_NOT_SUPPORTED
#define org_openni_NativeMethods_STATUS_NOT_SUPPORTED 3L
#undef org_openni_NativeMethods_STATUS_BAD_PARAMETER
#define org_openni_NativeMethods_STATUS_BAD_PARAMETER 4L
#undef org_openni_NativeMethods_STATUS_OUT_OF_FLOW
#define org_openni_NativeMethods_STATUS_OUT_OF_FLOW 5L
#undef org_openni_NativeMethods_STATUS_NO_DEVICE
#define org_openni_NativeMethods_STATUS_NO_DEVICE 6L
#undef org_openni_NativeMethods_STATUS_TIME_OUT
#define org_openni_NativeMethods_STATUS_TIME_OUT 102L
#undef org_openni_NativeMethods_STREAM_PROPERTY_CROPPING
#define org_openni_NativeMethods_STREAM_PROPERTY_CROPPING 0L
#undef org_openni_NativeMethods_STREAM_PROPERTY_HORIZONTAL_FOV
#define org_openni_NativeMethods_STREAM_PROPERTY_HORIZONTAL_FOV 1L
#undef org_openni_NativeMethods_STREAM_PROPERTY_VERTICAL_FOV
#define org_openni_NativeMethods_STREAM_PROPERTY_VERTICAL_FOV 2L
#undef org_openni_NativeMethods_STREAM_PROPERTY_MAX_VALUE
#define org_openni_NativeMethods_STREAM_PROPERTY_MAX_VALUE 4L
#undef org_openni_NativeMethods_STREAM_PROPERTY_MIN_VALUE
#define org_openni_NativeMethods_STREAM_PROPERTY_MIN_VALUE 5L
#undef org_openni_NativeMethods_STREAM_PROPERTY_STRIDE
#define org_openni_NativeMethods_STREAM_PROPERTY_STRIDE 6L
#undef org_openni_NativeMethods_STREAM_PROPERTY_MIRRORING
#define org_openni_NativeMethods_STREAM_PROPERTY_MIRRORING 7L
#undef org_openni_NativeMethods_STREAM_PROPERTY_NUMBER_OF_FRAMES
#define org_openni_NativeMethods_STREAM_PROPERTY_NUMBER_OF_FRAMES 8L
#undef org_openni_NativeMethods_STREAM_PROPERTY_AUTO_EXPOSURE
#define org_openni_NativeMethods_STREAM_PROPERTY_AUTO_EXPOSURE 100L
#undef org_openni_NativeMethods_STREAM_PROPERTY_AUTO_WHITE_BALANCE
#define org_openni_NativeMethods_STREAM_PROPERTY_AUTO_WHITE_BALANCE 101L
#undef org_openni_NativeMethods_STREAM_PROPERTY_EXPOSURE
#define org_openni_NativeMethods_STREAM_PROPERTY_EXPOSURE 102L
#undef org_openni_NativeMethods_STREAM_PROPERTY_GAIN
#define org_openni_NativeMethods_STREAM_PROPERTY_GAIN 103L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_FIRMWARE_VERSION
#define org_openni_NativeMethods_DEVICE_PROPERTY_FIRMWARE_VERSION 0L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_DRIVER_VERSION
#define org_openni_NativeMethods_DEVICE_PROPERTY_DRIVER_VERSION 1L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_HARDWARE_VERSION
#define org_openni_NativeMethods_DEVICE_PROPERTY_HARDWARE_VERSION 2L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_SERIAL_NUMBER
#define org_openni_NativeMethods_DEVICE_PROPERTY_SERIAL_NUMBER 3L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_ERROR_STATE
#define org_openni_NativeMethods_DEVICE_PROPERTY_ERROR_STATE 4L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_IMAGE_REGISTRATION
#define org_openni_NativeMethods_DEVICE_PROPERTY_IMAGE_REGISTRATION 5L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_PLAYBACK_SPEED
#define org_openni_NativeMethods_DEVICE_PROPERTY_PLAYBACK_SPEED 100L
#undef org_openni_NativeMethods_DEVICE_PROPERTY_PLAYBACK_REPEAT_ENABLED
#define org_openni_NativeMethods_DEVICE_PROPERTY_PLAYBACK_REPEAT_ENABLED 101L
#undef org_openni_NativeMethods_DEVICE_COMMAND_SEEK
#define org_openni_NativeMethods_DEVICE_COMMAND_SEEK 1L
/*
 * Class:     org_openni_NativeMethods
 * Method:    oniFrameRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniFrameRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniFrameAddRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniFrameAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceCreateStream
 * Signature: (JILorg/openni/VideoStream;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceCreateStream
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamDestroy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniStreamDestroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniStreamStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamReadFrame
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamReadFrame
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    getCropping
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_getCropping
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    setCropping
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_setCropping
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    isCroppingSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_isCroppingSupported
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    resetCropping
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_resetCropping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    getVideoMode
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_getVideoMode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    setVideoMode
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_setVideoMode
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamGetSensorInfo
 * Signature: (J)Lorg/openni/SensorInfo;
 */
JNIEXPORT jobject JNICALL Java_org_openni_NativeMethods_oniStreamGetSensorInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    hasSensor
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_hasSensor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamGetIntProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamGetIntProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamGetBoolProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamGetBoolProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamGetFloatProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamGetFloatProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamSetProperty
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamSetProperty__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamSetProperty
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamSetProperty__JIZ
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamSetProperty
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniStreamSetProperty__JIF
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniStreamIsPropertySupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_oniStreamIsPropertySupported
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetSensorInfo
 * Signature: (JI)Lorg/openni/SensorInfo;
 */
JNIEXPORT jobject JNICALL Java_org_openni_NativeMethods_oniDeviceGetSensorInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceEnableDepthColorSync
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceEnableDepthColorSync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceDisableDepthColorSync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniDeviceDisableDepthColorSync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetDepthColorSyncEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_oniDeviceGetDepthColorSyncEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    seek
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_seek
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    isImageRegistrationModeSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_isImageRegistrationModeSupported
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    getImageRegistrationMode
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_getImageRegistrationMode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    setImageRegistrationMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_setImageRegistrationMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetInfo
 * Signature: (J)Lorg/openni/DeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_org_openni_NativeMethods_oniDeviceGetInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniRecorderStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniRecorderStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniRecorderDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniRecorderDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniRecorderStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniRecorderStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniRecorderAttachStream
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniRecorderAttachStream
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetIntProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceGetIntProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetBoolProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceGetBoolProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceGetFloatProperty
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceGetFloatProperty
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceSetProperty
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceSetProperty__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceSetProperty
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceSetProperty__JIZ
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceSetProperty
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceSetProperty__JIF
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceIsPropertySupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_oniDeviceIsPropertySupported
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceIsCommandSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_oniDeviceIsCommandSupported
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniInitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_oniShutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniGetVersion
 * Signature: ()Lorg/openni/Version;
 */
JNIEXPORT jobject JNICALL Java_org_openni_NativeMethods_oniGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniGetExtendedError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_oniGetExtendedError
  (JNIEnv *, jclass);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniGetDeviceList
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniGetDeviceList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniWaitForAnyStream
 * Signature: ([JLorg/openni/OutArg;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_oniWaitForAnyStream
  (JNIEnv *, jclass, jlongArray, jobject, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniCoordinateConverterWorldToDepth
 * Signature: (JFFFLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniCoordinateConverterWorldToDepth
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniCoordinateConverterDepthToWorld
 * Signature: (JFFFLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniCoordinateConverterDepthToWorld
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniCoordinateConverterDepthToColor
 * Signature: (JJIISLorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniCoordinateConverterDepthToColor
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jshort, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniCreateRecorder
 * Signature: (Ljava/lang/String;Lorg/openni/Recorder;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniCreateRecorder
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceOpen
 * Signature: (Ljava/lang/String;Lorg/openni/Device;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceOpen__Ljava_lang_String_2Lorg_openni_Device_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceOpen
 * Signature: (Lorg/openni/Device;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceOpen__Lorg_openni_Device_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniDeviceClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniDeviceClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniSetLogOutputFolder
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniSetLogOutputFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniGetLogFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_oniGetLogFileName
  (JNIEnv *, jclass);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniSetLogMinSeverity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniSetLogMinSeverity
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniSetLogConsoleOutput
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniSetLogConsoleOutput
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniSetLogFileOutput
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniSetLogFileOutput
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    oniSetLogAndroidOutput
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_oniSetLogAndroidOutput
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif

#endif // ORG_OPENNI_NATIVEMETHODS_H
