/*****************************************************************************
*                                                                            *
*  OpenNI 2.x Alpha                                                          *
*  Copyright (C) 2012 PrimeSense Ltd.                                        *
*                                                                            *
*  This file is part of OpenNI.                                              *
*                                                                            *
*  Licensed under the Apache License, Version 2.0 (the "License");           *
*  you may not use this file except in compliance with the License.          *
*  You may obtain a copy of the License at                                   *
*                                                                            *
*      http://www.apache.org/licenses/LICENSE-2.0                            *
*                                                                            *
*  Unless required by applicable law or agreed to in writing, software       *
*  distributed under the License is distributed on an "AS IS" BASIS,         *
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
*  See the License for the specific language governing permissions and       *
*  limitations under the License.                                            *
*                                                                            *
*****************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef ORG_OPENNI_ANDROID_OPENNIVIEW_RENDERER_H
#define ORG_OPENNI_ANDROID_OPENNIVIEW_RENDERER_H

#include <jni.h>
/* Header for class org_openni_android_OpenNIView_Renderer */

#ifndef _Included_org_openni_android_OpenNIView_Renderer
#define _Included_org_openni_android_OpenNIView_Renderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif

#endif // ORG_OPENNI_ANDROID_OPENNIVIEW_RENDERER_H
