/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openni_android_OpenNIView_Renderer */

#ifndef _Included_org_openni_android_OpenNIView_Renderer
#define _Included_org_openni_android_OpenNIView_Renderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
