include ../../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../../Bin

INC_DIRS = \
	. \
	../../../Include \
	../../../ThirdParty/PSCommon/XnLib/Include

SRC_FILES = *.cpp

USED_LIBS += OpenNI2 

LIB_NAME = OpenNI2.jni

CFLAGS += -Wall

include ../../../ThirdParty/PSCommon/BuildSystem/CommonCppMakefile
